2023-08-20 23:50:47.805 - app - ERROR - _connect:76 - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v12-20020a17090a458c00b00265c742a262sm4666076pjg.4 - gsmtp')
2023-08-20 23:50:47.807 - app - INFO - _connect:78 - 
	Type: Mail Sender 
	Connection to server: (smtp.gmail.com, 465) 
	Username : ashishsingh50899@gmail.com 
	Connected (status): False

2023-08-20 23:50:47.808 - app - ERROR - retry:42 - Function send_all raised ConnectionError. Retrying (1/3)...
2023-08-20 23:50:50.103 - app - ERROR - _connect:76 - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v12-20020a17090a458c00b00265c742a262sm4666076pjg.4 - gsmtp')
2023-08-20 23:50:50.104 - app - INFO - _connect:78 - 
	Type: Mail Sender 
	Connection to server: (smtp.gmail.com, 465) 
	Username : ashishsingh50899@gmail.com 
	Connected (status): False

2023-08-20 23:50:50.105 - app - ERROR - retry:42 - Function send_all raised ConnectionError. Retrying (2/3)...
2023-08-20 23:50:52.423 - app - ERROR - _connect:76 - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v12-20020a17090a458c00b00265c742a262sm4666076pjg.4 - gsmtp')
2023-08-20 23:50:52.424 - app - INFO - _connect:78 - 
	Type: Mail Sender 
	Connection to server: (smtp.gmail.com, 465) 
	Username : ashishsingh50899@gmail.com 
	Connected (status): False

2023-08-20 23:50:52.424 - app - ERROR - retry:42 - Function send_all raised ConnectionError. Retrying (3/3)...
2023-08-20 23:50:54.743 - app - ERROR - _connect:76 - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v12-20020a17090a458c00b00265c742a262sm4666076pjg.4 - gsmtp')
2023-08-20 23:50:54.743 - app - INFO - _connect:78 - 
	Type: Mail Sender 
	Connection to server: (smtp.gmail.com, 465) 
	Username : ashishsingh50899@gmail.com 
	Connected (status): False

2023-08-20 23:50:54.744 - app - ERROR - retry:42 - Function send_all raised ConnectionError. Retrying (4/3)...
2023-08-20 23:50:54.744 - app - ERROR - exceptions:23 - send_all error : Not connected to any server. Try self.connect() first
