2023-08-20 23:56:57.048 - app - ERROR - _connect:76 - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ij27-20020a170902ab5b00b001b53c8659fesm5495624plb.30 - gsmtp')
2023-08-20 23:56:57.049 - app - INFO - _connect:78 - 
	Type: Mail Sender 
	Connection to server: (smtp.gmail.com, 465) 
	Username : ashishsingh50899@gmail.com 
	Connected (status): False

2023-08-20 23:56:57.050 - app - ERROR - retry:43 - Function send_all raised ConnectionError. Retrying (1/3)...
2023-08-20 23:56:59.375 - app - ERROR - _connect:76 - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ij27-20020a170902ab5b00b001b53c8659fesm5495624plb.30 - gsmtp')
2023-08-20 23:56:59.376 - app - INFO - _connect:78 - 
	Type: Mail Sender 
	Connection to server: (smtp.gmail.com, 465) 
	Username : ashishsingh50899@gmail.com 
	Connected (status): False

2023-08-20 23:56:59.377 - app - ERROR - retry:43 - Function send_all raised ConnectionError. Retrying (2/3)...
2023-08-20 23:57:01.699 - app - ERROR - _connect:76 - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ij27-20020a170902ab5b00b001b53c8659fesm5495624plb.30 - gsmtp')
2023-08-20 23:57:01.700 - app - INFO - _connect:78 - 
	Type: Mail Sender 
	Connection to server: (smtp.gmail.com, 465) 
	Username : ashishsingh50899@gmail.com 
	Connected (status): False

2023-08-20 23:57:01.700 - app - ERROR - retry:43 - Function send_all raised ConnectionError. Retrying (3/3)...
2023-08-20 23:57:04.066 - app - ERROR - _connect:76 - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ij27-20020a170902ab5b00b001b53c8659fesm5495624plb.30 - gsmtp')
2023-08-20 23:57:04.068 - app - INFO - _connect:78 - 
	Type: Mail Sender 
	Connection to server: (smtp.gmail.com, 465) 
	Username : ashishsingh50899@gmail.com 
	Connected (status): False

2023-08-20 23:57:04.069 - app - ERROR - exceptions:23 - send_all error : Not connected to any server. Try self.connect() first
